name: ExpBottle
version: 1.0.0
main: com.example.expbottle.ExpBottlePlugin
api-version: 1.21
description: A plugin to convert experience to bottles
author: YourName

commands:
  expbottle:
    description: Experience bottle commands
    usage: /<command> [bottle <amount>]
    permission: expbottle.use
    permission-message: You don't have permission to use this command

permissions:
  expbottle.use:
    description: Allows using experience bottle commands
    default: true
